baseurl: "https://xiaoshuchong.netlify.app/"
languageCode: "zh-CN"
title: "READER"
theme: "hugo-xmag"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true
paginate: 9

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: 首页
      url: /
      weight: 1
    - name: 关于
      url: /about/
      weight: 2
    # - name: 分类
    #   url: /categories/
    #   weight: 3
    # - name: 标签
    #   url: /tags/
    #   weight: 4
    - name: 文章
      url: /archives/
      weight: 5
    # - name: 搜索
    #   url: /search/
    #   weight: 6
    - name: 订阅
      url: /index.xml
      weight: 7


params:
  description: "这是小书虫和 TA 的朋友们读书群的博客。"
  footer: "&copy; 小书虫和TA的朋友们 2022 - 2023 | [Github](https://github.com/Shitao5/shuchong-blog)"
  github_edit: "https://github.com/Shitao5/shuchong-blog/edit/main/content/"
  summary_length: 200
  text:
    back: "&larr; 返回首页"
    edit: "编辑此页 &rarr;"
    truncated: "&hellip;"
    about_author: "关于作者"
    tags: "关键词："
    last_update: "最近更新于 "
    title_tags: "关键词列表"
    title_categories: "栏目分类"
    uncategorized: "未分类"
    author_delimiter: " / "

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
